// Package swagger Code generated by swag; DO NOT EDIT.
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "title": "GoLearn API",
        "description": "Uzaktan Eğitim Platformu API - Go + Gin + GORM + JWT + WebSocket",
        "contact": {
            "name": "GoLearn API Support"
        },
        "version": "1.0"
    },
    "host": "localhost:8080",
    "basePath": "/api/v1",
    "paths": {
        "/auth/register": {
            "post": {
                "description": "Register a new user with name, email, password and role",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Auth"],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Register request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["name", "email", "password", "role"],
                            "properties": {
                                "name": {"type": "string"},
                                "email": {"type": "string"},
                                "password": {"type": "string", "minLength": 6},
                                "role": {"type": "string", "enum": ["teacher", "student"]}
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {"description": "User registered successfully"},
                    "400": {"description": "Bad request"},
                    "409": {"description": "Email already registered"}
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Login with email and password to get JWT token",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Auth"],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "Login request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["email", "password"],
                            "properties": {
                                "email": {"type": "string"},
                                "password": {"type": "string"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {"description": "Login successful, returns JWT token"},
                    "401": {"description": "Invalid email or password"}
                }
            }
        },
        "/courses": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Get all courses with pagination, filtering and sorting",
                "produces": ["application/json"],
                "tags": ["Courses"],
                "summary": "List courses",
                "parameters": [
                    {"type": "integer", "name": "page", "in": "query"},
                    {"type": "integer", "name": "limit", "in": "query"},
                    {"type": "string", "name": "category", "in": "query"},
                    {"type": "string", "name": "sort", "in": "query"}
                ],
                "responses": {
                    "200": {"description": "Paginated course list"}
                }
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Create a new course (teacher only)",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Courses"],
                "summary": "Create course",
                "parameters": [
                    {
                        "description": "Course data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["title"],
                            "properties": {
                                "title": {"type": "string"},
                                "description": {"type": "string"},
                                "category": {"type": "string"}
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {"description": "Course created"},
                    "403": {"description": "Forbidden"}
                }
            }
        },
        "/courses/{id}": {
            "get": {
                "security": [{"BearerAuth": []}],
                "tags": ["Courses"],
                "summary": "Get course by ID",
                "parameters": [{"type": "integer", "name": "id", "in": "path", "required": true}],
                "responses": {
                    "200": {"description": "Course details"},
                    "404": {"description": "Not found"}
                }
            },
            "put": {
                "security": [{"BearerAuth": []}],
                "tags": ["Courses"],
                "summary": "Update course (owner only)",
                "parameters": [
                    {"type": "integer", "name": "id", "in": "path", "required": true},
                    {"description": "Update data", "name": "body", "in": "body", "required": true, "schema": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}, "category": {"type": "string"}}}}
                ],
                "responses": {
                    "200": {"description": "Updated"},
                    "403": {"description": "Forbidden"},
                    "404": {"description": "Not found"}
                }
            },
            "delete": {
                "security": [{"BearerAuth": []}],
                "tags": ["Courses"],
                "summary": "Delete course (owner only)",
                "parameters": [{"type": "integer", "name": "id", "in": "path", "required": true}],
                "responses": {
                    "200": {"description": "Deleted"},
                    "403": {"description": "Forbidden"},
                    "404": {"description": "Not found"}
                }
            }
        },
        "/courses/{id}/enroll": {
            "post": {
                "security": [{"BearerAuth": []}],
                "tags": ["Courses"],
                "summary": "Enroll in a course (student only)",
                "parameters": [{"type": "integer", "name": "id", "in": "path", "required": true}],
                "responses": {
                    "201": {"description": "Enrolled"},
                    "409": {"description": "Already enrolled"}
                }
            }
        },
        "/courses/{id}/lessons": {
            "get": {
                "security": [{"BearerAuth": []}],
                "tags": ["Lessons"],
                "summary": "List lessons for a course",
                "parameters": [{"type": "integer", "name": "id", "in": "path", "required": true}],
                "responses": {"200": {"description": "Lesson list"}}
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "tags": ["Lessons"],
                "summary": "Create lesson (teacher, owner only)",
                "parameters": [
                    {"type": "integer", "name": "id", "in": "path", "required": true},
                    {"description": "Lesson data", "name": "body", "in": "body", "required": true, "schema": {"type": "object", "required": ["title"], "properties": {"title": {"type": "string"}, "content": {"type": "string"}, "video_url": {"type": "string"}, "order": {"type": "integer"}}}}
                ],
                "responses": {"201": {"description": "Created"}, "403": {"description": "Forbidden"}}
            }
        },
        "/courses/{id}/lessons/{lessonId}": {
            "get": {
                "security": [{"BearerAuth": []}],
                "tags": ["Lessons"],
                "summary": "Get lesson by ID",
                "parameters": [
                    {"type": "integer", "name": "id", "in": "path", "required": true},
                    {"type": "integer", "name": "lessonId", "in": "path", "required": true}
                ],
                "responses": {"200": {"description": "Lesson detail"}, "404": {"description": "Not found"}}
            },
            "put": {
                "security": [{"BearerAuth": []}],
                "tags": ["Lessons"],
                "summary": "Update lesson (owner only)",
                "parameters": [
                    {"type": "integer", "name": "id", "in": "path", "required": true},
                    {"type": "integer", "name": "lessonId", "in": "path", "required": true},
                    {"description": "Update data", "name": "body", "in": "body", "required": true, "schema": {"type": "object", "properties": {"title": {"type": "string"}, "content": {"type": "string"}, "video_url": {"type": "string"}, "order": {"type": "integer"}}}}
                ],
                "responses": {"200": {"description": "Updated"}, "403": {"description": "Forbidden"}}
            },
            "delete": {
                "security": [{"BearerAuth": []}],
                "tags": ["Lessons"],
                "summary": "Delete lesson (owner only)",
                "parameters": [
                    {"type": "integer", "name": "id", "in": "path", "required": true},
                    {"type": "integer", "name": "lessonId", "in": "path", "required": true}
                ],
                "responses": {"200": {"description": "Deleted"}, "403": {"description": "Forbidden"}}
            }
        },
        "/courses/{id}/quizzes": {
            "get": {
                "security": [{"BearerAuth": []}],
                "tags": ["Quizzes"],
                "summary": "List quizzes for a course",
                "parameters": [{"type": "integer", "name": "id", "in": "path", "required": true}],
                "responses": {"200": {"description": "Quiz list"}}
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "tags": ["Quizzes"],
                "summary": "Create quiz with questions (teacher, owner only)",
                "parameters": [
                    {"type": "integer", "name": "id", "in": "path", "required": true},
                    {"description": "Quiz data", "name": "body", "in": "body", "required": true, "schema": {"type": "object", "required": ["title", "questions"], "properties": {"title": {"type": "string"}, "questions": {"type": "array", "items": {"type": "object", "properties": {"text": {"type": "string"}, "correct_answer": {"type": "string"}, "choices": {"type": "array", "items": {"type": "object", "properties": {"label": {"type": "string"}, "text": {"type": "string"}}}}}}}}}}
                ],
                "responses": {"201": {"description": "Created"}, "403": {"description": "Forbidden"}}
            }
        },
        "/courses/{id}/quizzes/{quizId}": {
            "get": {
                "security": [{"BearerAuth": []}],
                "tags": ["Quizzes"],
                "summary": "Get quiz by ID with questions",
                "parameters": [
                    {"type": "integer", "name": "id", "in": "path", "required": true},
                    {"type": "integer", "name": "quizId", "in": "path", "required": true}
                ],
                "responses": {"200": {"description": "Quiz detail"}, "404": {"description": "Not found"}}
            }
        },
        "/courses/{id}/quizzes/{quizId}/submit": {
            "post": {
                "security": [{"BearerAuth": []}],
                "tags": ["Quizzes"],
                "summary": "Submit quiz answers (student only)",
                "parameters": [
                    {"type": "integer", "name": "id", "in": "path", "required": true},
                    {"type": "integer", "name": "quizId", "in": "path", "required": true},
                    {"description": "Answers", "name": "body", "in": "body", "required": true, "schema": {"type": "object", "required": ["answers"], "properties": {"answers": {"type": "array", "items": {"type": "object", "properties": {"question_id": {"type": "integer"}, "answer": {"type": "string"}}}}}}}
                ],
                "responses": {"200": {"description": "Quiz result with score"}}
            }
        },
        "/courses/{id}/quizzes/{quizId}/results": {
            "get": {
                "security": [{"BearerAuth": []}],
                "tags": ["Quizzes"],
                "summary": "Get quiz results",
                "parameters": [
                    {"type": "integer", "name": "id", "in": "path", "required": true},
                    {"type": "integer", "name": "quizId", "in": "path", "required": true}
                ],
                "responses": {"200": {"description": "Results list"}}
            }
        },
        "/progress/complete": {
            "post": {
                "security": [{"BearerAuth": []}],
                "tags": ["Progress"],
                "summary": "Mark lesson as completed (student only)",
                "parameters": [
                    {"description": "Progress data", "name": "body", "in": "body", "required": true, "schema": {"type": "object", "required": ["course_id", "lesson_id"], "properties": {"course_id": {"type": "integer"}, "lesson_id": {"type": "integer"}}}}
                ],
                "responses": {"201": {"description": "Marked as completed"}, "409": {"description": "Already completed"}}
            }
        },
        "/progress/courses/{id}": {
            "get": {
                "security": [{"BearerAuth": []}],
                "tags": ["Progress"],
                "summary": "Get course progress percentage",
                "parameters": [{"type": "integer", "name": "id", "in": "path", "required": true}],
                "responses": {"200": {"description": "Progress with percentage"}}
            }
        },
        "/ws/{roomId}": {
            "get": {
                "security": [{"BearerAuth": []}],
                "tags": ["WebSocket"],
                "summary": "Join a live classroom chat room via WebSocket",
                "parameters": [
                    {"type": "string", "name": "roomId", "in": "path", "required": true},
                    {"type": "string", "name": "username", "in": "query"}
                ],
                "responses": {"101": {"description": "Switching Protocols - WebSocket connection established"}}
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "GoLearn API",
	Description:      "Uzaktan Eğitim Platformu API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
